FROM centos:centos7
MAINTAINER alok upadhyay <alokin.ntl@gmail.com>
ENV SSH_USER target
RUN yum -y update; yum clean all
RUN yum -y install openssh-server passwd; yum clean all
RUN mkdir /var/run/sshd

RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
RUN mkdir -p /root/.ssh/
COPY authorized_keys /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys
EXPOSE 22
ENTRYPOINT ["/usr/sbin/sshd", "-D"]
